[package]
name    = "example-01-basic-publish"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
bus-core           = { workspace = true }
bus-nats           = { workspace = true }
eventbus-nats = { workspace = true, features = ["nats-kv-inbox"] }
serde              = { workspace = true, features = ["derive"] }
tokio              = { workspace = true }
tracing-subscriber = "0.3"
